version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/root/persist/mariadb_data:/bitnami/mariadb'
  ghost:
    image: bitnami/ghost:latest
    ports:
      - '80:2368'
    volumes:
      - '/root/persist/ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb