version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/root/persist/mariadb_data:/bitnami/mariadb'
  application:
    image: bitnami/ghost:latest
    ports:
      - '80:2368'
    volumes:
      - '/root/persist/ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb
  wordpress:
    image: bitnami/wordpress:latest
    depends_on:
      - mariadb
    ports:
      - '81:80'
      - '443:443'
    environment:
      - WORDPRESS_PASSWORD=orion123@
    volumes:
      - /root/persist/wordpress_data:/bitnami/wordpress
      - /root/persist/apache_data:/bitnami/apache      